remote_theme: jekyll-theme-plain/jekyll-theme-plain

lang: en-US
title: yuuki
url: https://yuukikonno.com
license_url: https://creativecommons.org/licenses/by-sa/4.0/
stylesheets:
  - default.css

# Page permalinks
collections:
  pages:
    output: true
    permalink: /:title/

# Post permalinks
permalink: /blog/:title

# Front matter defaults for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      stylesheets:
        - post.css
      title: "" # sets the URL as the title

include:
  - .nojekyll
