title: yuuki's blog
url: https://yuukikonno.com
license_url: https://creativecommons.org/licenses/by-sa/4.0/

permalink: /blog/:title

collections:
  pages:
    output: true
    permalink: /:title/

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: plain-text-post

remote_theme: jekyll-theme-blank/jekyll-theme-blank
